language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
# Install the dependencies of vcs-repo-mgr before running the test suite.
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y bzr bzrtools git mercurial
install:
  - pip install coveralls
  - python setup.py install
script:
  - make check
  - coverage run --source=vcs_repo_mgr setup.py test
after_success:
  coveralls
