language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
# Install the dependencies of vcs-repo-mgr before running the test suite.
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y bzr bzrtools git mercurial
install:
  - pip install pip-accel
  - pip-accel install coveralls
  - pip-accel install .
script:
  - make check
  - make test
after_success:
  coveralls
